import { test, expect } from "../src/fixtures/test";

test("@smoke loads saucedemo login page", async ({ page }) => {
  await page.goto("/"); // uses baseURL from env
  await expect(page).toHaveTitle(/Swag Labs/);
  await expect(page.locator(".login_logo")).toHaveText("Swag Labs");
});

test("@regression login page shows expected UI", async ({ page }) => {
  await page.goto("/");

  await expect(page).toHaveTitle(/Swag Labs/);
  await expect(page.locator(".login_logo")).toHaveText("Swag Labs");

  await expect(page.locator('[data-test="username"]')).toBeVisible();
  await expect(page.locator('[data-test="password"]')).toBeVisible();
  await expect(page.locator('[data-test="login-button"]')).toBeVisible();
});

// Uses storageState/standard_user.json (generated by: npm run auth:state)
test.use({ auth: true });

test("@auth inventory opens with storageState", async ({ page }) => {
  await page.goto("/inventory.html");
  await expect(page).toHaveURL(/inventory\.html/);
  await expect(page.locator('[data-test="title"]')).toHaveText("Products");
});